[package]
name = "coordinator"
version = "0.1.0"
authors = ["CodeChain Team <hi@codechain.io>"]
edition = "2018"

[dependencies]
ctypes = { package = "codechain-types", path = "../types" }
ckey = {package = "codechain-key", path = "../key" }
ccrypto = { package = "codechain-crypto", git = "https://github.com/CodeChain-io/rust-codechain-crypto.git", version = "0.2" }
primitives = { git = "https://github.com/CodeChain-io/rust-codechain-primitives.git", version = "0.4" }
rlp = { git = "https://github.com/CodeChain-io/rlp.git", version = "0.4" }
actix-web = "2.0"
actix-cors = "0.2.0"
queryst = "1"
juniper = { version = "0.14.2", features = ["expose-test-schema", "serde_json"] }


[dev-dependencies]
actix-rt = "1.1.1"
actix-http = "1.0.1"
async-graphql = "1.11.3"
futures = "0.3.5"
starwars = { version = "0.1.0",  git = "https://github.com/async-graphql/examples.git" }
tokio = "0.2.20"
serde_json = "1.0.53"
serde_derive = "1.0.110"
serde = "1.0.110"
