[package]
 name = "orderer"
 version = "0.1.0"
 authors = ["CodeChain Team <hi@codechain.io>"]
 edition = "2018"

[dependencies]
coordinator = { path = "../../coordinator" }
ctypes = { package = "codechain-types", path = "../../types" }
ckey = { package = "codechain-key", path = "../../key" }
